<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRoute } from 'vue-router';
import { categories } from './data';
import { clubCatalog as clubs } from './business';
import { state, dateLabel, toggleFavorite } from './store';
import Icon from './Icon.vue';
const route = useRoute();
const activityMode = computed(() => route.path === '/activities');
const recruitmentMode = computed(() => route.path === '/recruitment');
const category = ref('全部'); const keyword = ref(''); const openOnly = ref(false);
const matchingClubs = computed(() => clubs.value.filter(c => (!recruitmentMode.value || c.recruiting) && (category.value === '全部' || c.category === category.value) && `${c.name} ${c.tags.join(' ')} ${c.description}`.includes(keyword.value.trim())));
const activities = computed(() => state.activities.filter(a => a.status === 'published' && (category.value === '全部' || a.category === category.value) && (!openOnly.value || a.enrolled < a.capacity) && `${a.title} ${a.location} ${clubs.value.find(c => c.id === a.clubId)?.name}`.includes(keyword.value.trim())).sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)));
</script>
<template>
  <div class="p-page-heading"><p class="p-kicker">{{ activityMode ? 'CAMPUS EVENTS' : recruitmentMode ? 'JOIN SOMETHING YOU LOVE' : 'FIND YOUR COMMUNITY' }}</p><h1>{{ activityMode ? '把课余时间，留给喜欢的事。' : recruitmentMode ? '新故事，从加入一个社团开始。' : '在这里，找到同频的伙伴。' }}</h1><p>{{ activityMode ? '讲座、工作坊、户外和演出。选一场活动，走出日常。' : recruitmentMode ? '了解招新条件，表达你的兴趣。不需要完美的简历，带上热情就好。' : '从科技实践到文化艺术，每一种兴趣都有生长的地方。' }}</p></div>
  <section v-if="recruitmentMode" class="p-recruit-banner"><span class="p-big-symbol">JOIN<br>US.</span><div><span class="p-chip white">秋季招新 · 示例</span><h2>你的第一位社团伙伴，正在等你。</h2><p>查看社团详情 → 填写申请 → 等待审核 → 加入社团</p></div><RouterLink to="/me" class="p-button light">查看我的申请<Icon name="arrow" /></RouterLink></section>
  <div class="p-filter-bar"><label class="p-search"><Icon name="search" /><input v-model="keyword" :aria-label="activityMode ? '搜索活动' : '搜索社团'" :placeholder="activityMode ? '搜索活动名称、地点或社团' : '搜索社团名称或兴趣，如摄影'" /></label><label v-if="activityMode" class="p-checkbox"><input v-model="openOnly" type="checkbox" />只看有名额</label><span v-else class="p-small">{{ matchingClubs.length }} 个{{ recruitmentMode ? '招新' : '示例' }}社团</span></div>
  <div class="p-filter-chips" aria-label="类别筛选"><button v-for="item in categories" :key="item" :class="{ selected: category === item }" @click="category = item">{{ item }}</button></div>
  <div v-if="!activityMode" class="p-club-grid"><article v-for="club in matchingClubs" :key="club.id" class="p-club-card"><RouterLink :to="`/clubs/${club.id}`" class="p-club-cover" :class="club.color"><span class="p-cover-type">{{ club.category }}</span><strong>{{ club.mark }}</strong><span class="p-cover-caption">{{ club.tags.join(' / ') }}</span><i>↗</i></RouterLink><div class="p-card-body"><div class="p-inline"><RouterLink :to="`/clubs/${club.id}`"><h3>{{ club.name }}</h3></RouterLink><button class="p-icon-button" :class="{ favorited: state.favorites.includes(club.id) }" :aria-label="`${state.favorites.includes(club.id) ? '取消收藏' : '收藏'}${club.name}`" :aria-pressed="state.favorites.includes(club.id)" @click="toggleFavorite(club.id)"><Icon name="heart" /></button></div><p>{{ club.slogan }}</p><div class="p-tags"><span v-for="tag in club.tags" :key="tag">{{ tag }}</span></div><div class="p-card-bottom"><span>{{ club.members }} 位伙伴</span><RouterLink :to="`/clubs/${club.id}`" class="p-chip" :class="club.recruiting ? 'green' : 'gray'">{{ club.recruiting ? '招新中 · 了解详情' : '招新已结束' }}</RouterLink></div></div></article></div>
  <div v-else class="p-activity-grid"><RouterLink v-for="activity in activities" :key="activity.id" :to="`/activities/${activity.id}`" class="p-activity-card"><div class="p-activity-cover" :class="clubs.find(c => c.id === activity.clubId)?.color"><span>{{ activity.category }}</span><strong>{{ activity.title }}</strong><div class="p-activity-cover-bottom"><span>{{ clubs.find(c => c.id === activity.clubId)?.name }}</span><Icon name="arrow" /></div></div><div class="p-card-body"><p class="p-meta"><Icon name="calendar" />{{ dateLabel(activity.date) }} · {{ activity.time }}</p><p class="p-meta"><Icon name="pin" />{{ activity.location }}</p><div class="p-card-bottom"><span>{{ activity.enrolled }} / {{ activity.capacity }} 人</span><span class="p-chip" :class="state.registrations.includes(activity.id) ? 'blue' : activity.enrolled >= activity.capacity ? 'gray' : 'green'">{{ state.registrations.includes(activity.id) ? '已报名' : activity.enrolled >= activity.capacity ? '名额已满' : '查看并报名' }}</span></div></div></RouterLink></div>
  <div v-if="activityMode ? !activities.length : !matchingClubs.length" class="p-empty"><Icon name="search" /><h3>暂时没有找到匹配结果</h3><p>换个关键词，或选择其他类别试试。</p><button class="p-button secondary" @click="keyword = ''; category = '全部'; openOnly = false">清除筛选</button></div>
</template>
