<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { clubs } from './data';
import { state } from './store';
import Icon from './Icon.vue';
import { publicPreview } from './public';
import { businessMode } from './business';
const route = useRoute();
const recommended = computed(() => clubs.filter(c => c.recruiting && c.tags.some(t => state.profile.interests.includes(t))).slice(0, 3));
</script>
<template>
  <template v-if="route.path === '/assistant'"><div class="p-page-heading"><p class="p-kicker">A LITTLE HELP, WHEN YOU NEED IT</p><h1>社团是主角，智能只是帮手。</h1><p>先用清楚的社团信息做选择，需要时再使用辅助能力。</p></div><div class="p-two-columns"><section class="p-panel"><span class="p-mini-icon"><Icon name="heart" /></span><h2>从你的兴趣，找到一些线索</h2><p>当前兴趣：{{ state.profile.interests.join('、') || '尚未选择' }}。下列结果仅按共同标签筛选，不使用 Embedding 或大模型。</p><RouterLink v-for="club in recommended" :key="club.id" :to="`/clubs/${club.id}`" class="p-list-item"><div><h3>{{ club.name }}</h3><p>共同兴趣：{{ club.tags.filter(t => state.profile.interests.includes(t)).join('、') }}</p></div><Icon name="arrow" /></RouterLink><p v-if="!recommended.length">暂无共同标签的招新社团，可以先设置兴趣偏好。</p><RouterLink to="/me" class="p-text-button">调整我的兴趣 ↗</RouterLink></section><section v-if="!publicPreview" class="p-panel"><span class="p-mini-icon"><Icon name="book" /></span><h2>资料问答：从原文中找答案</h2><p>现有后端提供资料上传、检索和来源展示。该功能需要业务服务与 AI 服务运行；本地模式返回原文摘录。</p><div class="p-callout">这里只提供真实联调入口，不用预设回答冒充 AI。</div><RouterLink to="/system/chat" class="p-button secondary">打开资料问答<Icon name="arrow" /></RouterLink><RouterLink to="/system/knowledge" class="p-text-button p-top-gap">管理公开测试资料 ↗</RouterLink></section><section v-else class="p-panel"><span class="p-mini-icon"><Icon name="book" /></span><h2>关于加入和参与</h2><p>先阅读社团的招新条件和活动安排，再选择申请或报名。</p><div class="p-callout">当前为纯前端原型，资料问答和 AI 活动规划未开放，不会调用大模型或后端。</div><RouterLink to="/recruitment" class="p-button secondary">查看招新社团</RouterLink></section></div><section class="p-panel"><h2>智能能力的边界</h2><p>未来的语义推荐、活动规划与工具调用属于计划实现。报名、入社审核、活动发布必须以正式业务规则和用户确认结果为准，不由模型直接决定。</p></section></template>
  <template v-else-if="businessMode"><div class="p-page-heading"><h1>一条真实入社业务，已经接通。</h1><p>当前为本地开发系统，不是学校正式平台。</p></div><section class="p-panel"><h2>如何体验</h2><ol class="p-guide-list"><li>用学生账号登录，进入社团详情提交申请。</li><li>在“我的”查看待审核记录；退出学生账号。</li><li>用对应社团负责人账号登录，在工作台审核。</li><li>进入成员名单确认入社；重新登录学生账号查看结果。</li></ol><RouterLink to="/login" class="p-button">打开登录页</RouterLink></section><section class="p-panel"><h2>已接通与未接通</h2><p>登录、社团查询、入社申请、审核、撤回和成员关系使用后端数据库；默认 H2 文件库，服务重启后业务记录仍保留，但需要重新登录。</p><p>所有账号和社团资料为虚构测试数据。活动报名、收藏和消息仍为浏览器演示；正式活动发布、经费管理、通知、推荐和 Agent 编排尚未实现。AI 资料联调仍是公开测试资料，尚未做完整资料权限隔离，因此不得公开部署。</p><p>已保存的纯前端原型保持独立，通过 start-prototype.ps1 启动；本开发模式通过 start-dev.ps1 启动，不开放公网。</p></section></template>
  <template v-else><div class="p-page-heading"><p class="p-kicker">PROTOTYPE WALKTHROUGH</p><h1>先看见产品，再逐步实现。</h1><p>这是一套响应式交互原型，用来确认页面、信息和业务流程。</p></div><div class="p-two-columns"><section class="p-panel"><h2>学生端 · 找到自己的社团</h2><ol class="p-guide-list"><li>进入社团广场，搜索、筛选、收藏社团。</li><li>查看社团详情，填写理由并提交模拟申请。</li><li>到个人中心查看申请状态与我的社团。</li><li>选择活动，确认模拟报名，查看或取消报名。</li><li>在消息中心查看申请和报名结果。</li></ol><RouterLink to="/clubs" class="p-button">从社团广场开始<Icon name="arrow" /></RouterLink></section><section class="p-panel"><h2>负责人端 · 管理社团日常</h2><ol class="p-guide-list"><li>点击顶部“负责人工作台”，选择管理社团。</li><li>查看学生申请，通过或拒绝并填写意见。</li><li>审核通过后查看新增成员。</li><li>新建活动，保存草稿，再确认模拟发布。</li><li>回到学生端查看活动、报名，核对名单。</li></ol><RouterLink to="/manage" class="p-button secondary">体验负责人工作台<Icon name="arrow" /></RouterLink></section></div><section class="p-panel"><h2>请先了解这些边界</h2><div class="p-info-line"><span>数据</span><p>全部为虚构演示，存储在当前浏览器 localStorage。不同设备、不同浏览器、不同访问地址的数据不共享。</p></div><div class="p-info-line"><span>身份</span><p>仅演示身份切换，没有真实登录、权限认证或跨用户协作。</p></div><div class="p-info-line"><span>后端</span><p v-if="publicPreview">这是独立的纯前端演示网页，没有后端接口、数据库或 AI 调用。演示记录不会提交给学校。</p><p v-else>产品原型不依赖后端或 AI 服务。正常开发模式已接通入社申请与审核；此原型模式仍使用浏览器模拟数据。</p></div><div class="p-info-line"><span>手机</span><p v-if="publicPreview">手机浏览器可打开临时 HTTPS 预览地址；通道开启时电脑必须保持运行。</p><p v-else>使用响应式网页。手机与电脑接入可互通的同一局域网后，使用电脑的局域网地址访问；电脑必须保持运行，防火墙需允许该端口。</p></div><div class="p-info-line"><span>经费与签到</span><p>经费只展示活动计划预算台账。实际报销、支付、扫码签到、学校级审批尚未实现，不作为这次原型的强制流程。</p></div></section></template>
</template>
