<script setup lang="ts">
import { computed } from 'vue';
import { clubCatalog as clubs } from './business';
import { state, dateLabel } from './store';
import Icon from './Icon.vue';
const upcoming = computed(() => state.activities.filter(a => a.status === 'published').slice(0, 3));
</script>
<template>
  <section class="p-hero"><div class="p-hero-copy"><p class="p-kicker">HELLO, CAMPUS LIFE / 秋季社团招新</p><h1>你的热爱，<br>在这里<span>有回应。</span></h1><p class="p-hero-description">从一个兴趣开始，遇见一群同频的人。<br>发现社团，参与活动，书写属于你的校园故事。</p><div class="p-actions"><RouterLink to="/clubs" class="p-button">寻找我的社团<Icon name="arrow" /></RouterLink><RouterLink to="/activities" class="p-text-button">看看近期活动 ↗</RouterLink></div><div class="p-hero-caption"><span class="p-stacked-avatars"><i>光</i><i>山</i><i>♪</i></span><span>不必很厉害，也可以从喜欢开始。</span></div></div>
    <div class="p-hero-art" aria-hidden="true"><span class="p-art-top">FIND YOUR PEOPLE.</span><div class="p-orbit"></div><div class="p-art-card p-art-card-one"><span>01 / CREATE</span><strong>把热爱<br>变成作品。</strong><div class="p-art-camera"><i></i></div><small>摄影 · 音乐 · 创作</small></div><div class="p-art-card p-art-card-two"><span>02 / EXPLORE</span><strong>和伙伴，<br>一起出发。</strong><div class="p-art-mountain">△</div><small>运动 · 户外 · 公益</small></div><svg class="p-art-star" viewBox="0 0 100 100"><path d="M50 0 61 35 100 50 61 61 50 100 35 61 0 50 35 35Z" fill="currentColor" /></svg><span class="p-art-bottom">A LITTLE INTEREST.<br>A WHOLE NEW WORLD.</span></div>
  </section>
  <section class="p-shortcuts"><RouterLink to="/recruitment"><Icon name="clubs" /><div><strong>招新进行时</strong><span>找到你的新伙伴</span></div><Icon name="arrow" /></RouterLink><RouterLink to="/activities"><Icon name="calendar" /><div><strong>这周去哪里</strong><span>给课余生活一点灵感</span></div><Icon name="arrow" /></RouterLink><RouterLink to="/me"><Icon name="heart" /><div><strong>我的校园足迹</strong><span>申请、报名与收藏</span></div><Icon name="arrow" /></RouterLink></section>
  <section class="p-section"><div class="p-section-head"><div><p class="p-kicker">CLUB SPOTLIGHT</p><h2>总有一个社团，与你合拍<span class="p-title-dot">.</span></h2></div><RouterLink to="/clubs" class="p-text-button">全部社团<Icon name="arrow" /></RouterLink></div><div class="p-club-grid"><RouterLink v-for="club in clubs.slice(0, 3)" :key="club.id" :to="`/clubs/${club.id}`" class="p-club-card"><div class="p-club-cover" :class="club.color"><span class="p-cover-type">{{ club.category }}</span><strong>{{ club.mark }}</strong><span class="p-cover-caption">{{ club.tags.join(' / ') }}</span><i>↗</i></div><div class="p-card-body"><div class="p-inline"><h3>{{ club.name }}</h3><span class="p-chip green">招新中</span></div><p>{{ club.slogan }}</p><div class="p-card-bottom"><span>{{ club.members }} 位伙伴</span><span>了解社团 ↗</span></div></div></RouterLink></div></section>
  <section class="p-section p-upcoming"><div class="p-section-head"><div><p class="p-kicker">MAKE TIME FOR SOMETHING GOOD</p><h2>下一站，精彩活动。</h2></div><RouterLink to="/activities" class="p-text-button">活动日历<Icon name="arrow" /></RouterLink></div><RouterLink v-for="activity in upcoming" :key="activity.id" :to="`/activities/${activity.id}`" class="p-event-row"><div class="p-date-box"><small>{{ Number(activity.date.slice(5, 7)) }}月</small><strong>{{ activity.date.slice(8, 10) }}</strong></div><div class="p-event-info"><span class="p-kicker">{{ clubs.find(c => c.id === activity.clubId)?.name }}</span><h3>{{ activity.title }}</h3><p>{{ dateLabel(activity.date) }} {{ activity.time }} · {{ activity.location }}</p></div><span class="p-chip" :class="activity.enrolled >= activity.capacity ? 'gray' : 'green'">{{ activity.enrolled >= activity.capacity ? '名额已满' : '可报名' }}</span><Icon name="arrow" /></RouterLink></section>
  <section class="p-assistant-strip"><div><span class="p-mini-icon"><Icon name="book" /></span><div><h3>关于社团，还有一点想了解？</h3><p>查看招新说明，或到资料助手中寻找答案。</p></div></div><RouterLink to="/assistant" class="p-text-button">打开辅助入口<Icon name="arrow" /></RouterLink></section>
</template>
