<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRoute } from 'vue-router';
import { clubs, type Activity } from './data';
import { state, review, toast, today, dateLabel, statusLabels, prototypeId, type Application } from './store';
import Icon from './Icon.vue';
import Modal from './Modal.vue';
const route = useRoute();
const section = computed(() => route.path.split('/')[2] || 'overview');
const club = computed(() => clubs.find(c => c.id === state.managedClub)!);
const requests = computed(() => state.applications.filter(a => a.clubId === state.managedClub));
const pending = computed(() => requests.value.filter(a => a.status === 'pending'));
const members = computed(() => requests.value.filter(a => a.status === 'approved'));
const activities = computed(() => state.activities.filter(a => a.clubId === state.managedClub));
const budget = computed(() => activities.value.reduce((sum, a) => sum + a.budget, 0));
const filter = ref('pending'); const selected = ref<Application>(); const modal = ref(''); const feedback = ref('');
const form = ref({ title: '', date: '2026-10-30', time: '15:00', location: '', capacity: 30, description: '', budget: 0 });
const formError = ref(''); const editingId = ref('');
const filteredRequests = computed(() => requests.value.filter(a => filter.value === 'all' || a.status === filter.value));
const headings: Record<string, [string, string]> = {
  overview: ['负责人工作台', '招新、成员和活动，在一个工作台中协作。'],
  recruitment: ['招新审核', '查看加入理由，给出明确的审核结果。'],
  members: ['成员管理', '审核通过的模拟申请，将自动出现在成员名单中。'],
  activities: ['活动管理', '先准备草稿，再由负责人确认发布。'],
  finance: ['经费台账', '轻量预算台账原型，不包含真实付款或报销审批。']
};
function openReview(item: Application) { selected.value = item; feedback.value = ''; modal.value = 'review'; }
function decide(approved: boolean) { if (selected.value) review(selected.value.id, approved, feedback.value); modal.value = ''; }
function newActivity() { editingId.value = ''; form.value = { title: '', date: '2026-10-30', time: '15:00', location: '', capacity: 30, description: '', budget: 0 }; formError.value = ''; modal.value = 'activity'; }
function editActivity(item: Activity) { editingId.value = item.id; form.value = { title: item.title, date: item.date, time: item.time, location: item.location, capacity: item.capacity, description: item.description, budget: item.budget }; formError.value = ''; modal.value = 'activity'; }
function saveActivity(publish: boolean) {
  const f = form.value;
  if (!f.title.trim() || !f.location.trim() || !f.description.trim() || !f.date || !f.time || !Number.isInteger(f.capacity) || f.capacity < 1 || f.capacity > 500 || !Number.isFinite(f.budget) || f.budget < 0) { formError.value = '请完整填写活动信息；人数为 1～500 的整数，预算不得为负。'; return; }
  if (new Date(`${f.date}T${f.time}`).getTime() <= Date.now()) { formError.value = '请选择未来的活动时间。'; return; }
  const existing = state.activities.find(a => a.id === editingId.value && a.clubId === state.managedClub);
  const value: Activity = { ...f, title: f.title.trim(), location: f.location.trim(), description: f.description.trim(), id: existing?.id || prototypeId(), clubId: state.managedClub, category: club.value.category, enrolled: existing?.enrolled || 0, agenda: existing?.agenda || [`${f.time} 集合与活动说明`, '按活动安排参与', '交流与活动小结'], status: publish ? 'published' : 'draft' };
  if (value.capacity < value.enrolled) { formError.value = '名额上限不能小于当前报名人数。'; return; }
  if (existing) Object.assign(existing, value); else state.activities.unshift(value);
  toast(publish ? '模拟活动已发布，学生端可以查看和报名' : '模拟草稿已保存，仅负责人可见'); modal.value = '';
}
</script>
<template>
  <div class="p-manager-heading"><div class="p-page-heading"><h1>{{ headings[section]?.[0] }}</h1><p>{{ headings[section]?.[1] }}</p></div><label class="p-club-selector">当前管理社团<select v-model="state.managedClub" aria-label="选择管理社团"><option v-for="item in clubs" :key="item.id" :value="item.id">{{ item.name }}</option></select></label></div>
  <template v-if="section === 'overview'"><div class="p-stat-grid"><section><strong>{{ pending.length }}</strong><span>待审核申请</span></section><section><strong>{{ members.length }}</strong><span>新增成员 · 演示</span></section><section><strong>{{ activities.filter(a => a.status === 'published').length }}</strong><span>已发布活动</span></section><section><strong>{{ activities.filter(a => a.status === 'draft').length }}</strong><span>活动草稿</span></section></div><div class="p-two-columns"><section class="p-panel"><div class="p-section-head"><h2>待办事项</h2><span class="p-chip gray">{{ today() }}</span></div><RouterLink to="/manage/recruitment" class="p-task-link"><span class="p-mini-icon"><Icon name="clubs" /></span><div><h3>回应新的入社申请</h3><p>{{ pending.length ? `有 ${pending.length} 份申请等待你的回复` : '暂无待审核申请，可先到学生端提交一份' }}</p></div><Icon name="arrow" /></RouterLink><RouterLink to="/manage/activities" class="p-task-link"><span class="p-mini-icon"><Icon name="calendar" /></span><div><h3>安排下一场社团活动</h3><p>编辑草稿、确认发布、查看报名记录</p></div><Icon name="arrow" /></RouterLink><RouterLink to="/manage/finance" class="p-task-link"><span class="p-mini-icon"><Icon name="book" /></span><div><h3>检查活动预算台账</h3><p>汇总计划预算，不涉及真实财务操作</p></div><Icon name="arrow" /></RouterLink></section><section class="p-panel"><div class="p-inline"><h2>{{ club.name }}</h2><span class="p-chip green">{{ club.recruiting ? '招新中' : '招新结束' }}</span></div><p>{{ club.description }}</p><div class="p-info-line"><span>常规时间</span><strong>{{ club.schedule }}</strong></div><div class="p-info-line"><span>活动地点</span><strong>{{ club.place }}</strong></div><RouterLink :to="`/clubs/${club.id}`" class="p-button secondary full">查看学生端社团页<Icon name="arrow" /></RouterLink></section></div></template>
  <template v-if="section === 'recruitment'"><div class="p-filter-chips"><button v-for="item in [{ id: 'pending', label: '待审核' }, { id: 'approved', label: '已通过' }, { id: 'rejected', label: '未通过' }, { id: 'all', label: '全部记录' }]" :key="item.id" :class="{ selected: filter === item.id }" :aria-pressed="filter === item.id" type="button" @click="filter = item.id">{{ item.label }}</button></div><section class="p-panel"><article v-for="item in filteredRequests" :key="item.id" class="p-list-item"><div><h3>{{ item.name }}<span v-if="item.mine" class="p-chip blue">学生端当前身份</span></h3><p>{{ item.major }} · {{ item.date }}</p><p>{{ item.reason }}</p><p v-if="item.feedback" class="p-review-feedback">审核意见：{{ item.feedback }}</p></div><button v-if="item.status === 'pending'" class="p-button secondary" @click="openReview(item)">查看并审核</button><span v-else class="p-chip" :class="item.status === 'approved' ? 'green' : 'gray'">{{ statusLabels[item.status] }}</span></article><div v-if="!filteredRequests.length" class="p-empty"><Icon name="check" /><h3>当前列表暂无申请</h3><p>可切到学生端申请加入{{ club.name }}，再回来体验审核。</p><RouterLink :to="`/clubs/${club.id}`" class="p-button secondary">前往社团详情 ↗</RouterLink></div></section></template>
  <template v-if="section === 'members'"><section class="p-panel"><div class="p-section-head"><h2>本原型新增成员</h2><span class="p-small">{{ members.length }} 人 · 不含宣传页示例人数</span></div><article v-for="item in members" :key="item.id" class="p-list-item"><span class="p-avatar">{{ item.name.slice(0, 1) }}</span><div class="p-grow"><h3>{{ item.name }}</h3><p>{{ item.major }} · 申请日期 {{ item.date }}</p></div><span class="p-chip green">成员 · 演示</span></article><div v-if="!members.length" class="p-empty"><Icon name="clubs" /><h3>等待第一位新伙伴加入</h3><p>审核通过申请后，成员名单会自动更新。</p><RouterLink to="/manage/recruitment" class="p-button secondary">前往招新审核 ↗</RouterLink></div></section></template>
  <template v-if="section === 'activities'"><div class="p-section-head"><h2>{{ club.name }}的活动</h2><button class="p-button" @click="newActivity"><Icon name="plus" />新建活动</button></div><section class="p-panel"><article v-for="item in activities" :key="item.id" class="p-list-item"><div class="p-grow"><h3>{{ item.title }}</h3><p>{{ dateLabel(item.date) }} {{ item.time }} · {{ item.location }}</p><p>报名 {{ item.enrolled }} / {{ item.capacity }} 人 · 预算 ¥{{ item.budget }}</p></div><div class="p-record-actions"><span class="p-chip" :class="item.status === 'published' ? 'green' : 'yellow'">{{ item.status === 'published' ? '已发布 · 演示' : '草稿' }}</span><button v-if="item.status === 'draft'" class="p-text-button" @click="editActivity(item)">编辑并发布</button><RouterLink v-else :to="`/activities/${item.id}`" class="p-text-button">查看学生端 ↗</RouterLink><button class="p-text-button" @click="editingId = item.id; modal = 'roster'">查看报名名单</button></div></article><div v-if="!activities.length" class="p-empty"><h3>准备你的第一场活动</h3><p>不需要先录入整套场地系统，填写活动地点即可。</p><button class="p-button secondary" @click="newActivity">新建活动</button></div></section></template>
  <template v-if="section === 'finance'"><div class="p-stat-grid p-three-stats"><section><strong>¥{{ budget.toLocaleString() }}</strong><span>计划预算合计</span></section><section><strong>{{ activities.length }}</strong><span>关联活动</span></section><section><strong>—</strong><span>实际支出 · 尚未接入</span></section></div><section class="p-panel"><h2>活动预算明细</h2><p class="p-small">此处汇总活动表单填写的计划预算，未实现支付、报销、审批或真实余额。</p><article v-for="item in activities" :key="item.id" class="p-list-item"><div><h3>{{ item.title }}</h3><p>{{ dateLabel(item.date) }} · {{ item.status === 'draft' ? '草稿预算' : '已发布活动预算' }}</p></div><strong>¥{{ item.budget.toLocaleString() }}</strong></article><p v-if="!activities.length" class="p-empty-text">暂无预算记录。创建活动时可填写计划预算。</p></section></template>
  <Modal v-if="modal === 'review' && selected" title="审核入社申请" @close="modal = ''"><h3>{{ selected.name }} · {{ selected.major }}</h3><p>{{ selected.reason }}</p><form class="p-form" @submit.prevent="decide(true)"><label>审核意见（可选）<textarea v-model="feedback" maxlength="300" rows="3" placeholder="欢迎加入，或说明本次未通过的原因。"></textarea></label><p class="p-small">通过后生成模拟成员关系；若为当前学生身份，结果会出现在消息中心。</p><div class="p-actions"><button type="button" class="p-button secondary" @click="decide(false)">暂不通过</button><button class="p-button">通过模拟申请<Icon name="check" /></button></div></form></Modal>
  <Modal v-if="modal === 'activity'" :title="editingId ? '编辑活动草稿' : '新建活动'" @close="modal = ''"><form class="p-form" @submit.prevent="saveActivity(true)"><label>活动名称<input v-model="form.title" required maxlength="60" placeholder="例如：校园摄影入门分享" /></label><div class="p-form-grid"><label>活动日期<input v-model="form.date" required type="date" /></label><label>开始时间<input v-model="form.time" required type="time" /></label></div><label>活动地点<input v-model="form.location" required maxlength="80" placeholder="直接填写地点，无需配置场地库" /></label><div class="p-form-grid"><label>人数上限<input v-model.number="form.capacity" required type="number" min="1" max="500" step="1" /></label><label>计划预算（元）<input v-model.number="form.budget" required type="number" min="0" max="100000" step="0.01" /></label></div><label>活动说明<textarea v-model="form.description" required maxlength="1000" rows="3" placeholder="写清活动内容、参与要求和注意事项。"></textarea></label><p v-if="formError" class="p-form-error" role="alert">{{ formError }}</p><p class="p-small">发布按钮就是本原型的人工确认；不会调用 AI 或发送真实通知。</p><div class="p-actions"><button class="p-button secondary" type="button" @click="saveActivity(false)">保存草稿</button><button class="p-button">确认并模拟发布<Icon name="arrow" /></button></div></form></Modal>
  <Modal v-if="modal === 'roster'" title="模拟报名名单" @close="modal = ''"><template v-if="state.registrations.includes(editingId)"><div class="p-list-item"><div><h3>{{ state.profile.name }}</h3><p>{{ state.profile.major }}</p></div><span class="p-chip green">已报名</span></div></template><p v-else>当前浏览器还没有学生报名记录。</p><p class="p-small">活动卡片中的初始人数为虚构统计，不对应个人名单；此处只列出本浏览器新增的模拟报名。</p></Modal>
</template>
